services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/projeto_ts_next?schema=public
      JWT_SECRET: supersecret
      NODE_ENV: development
    command: sh -c "sleep 10 && npx prisma migrate deploy && exec npx tsx watch src/server.ts"

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projeto_ts_next
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
